language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0
install: bundle install --without=integration
script: bundle exec rake test
branches:
  only:
  - master
notifications:
  slack:
    secure: VZScuI2MSVBnv0hy6DZyKwTTEnI78bqStXk1NwjAYzKY92pwCZMYHS4SLfRFeVZuIuO2p5DIvgybMvZYd/pvxX6G0djlxoTcDc+ZMpk1PdaLo89iDlNbiMhDyDOVa6gmEDWymIjPVCG+d3JVluDfR6F2IFNoSCNgL5kWScOBIow=
